AWSTemplateFormatVersion: '2010-09-09'
Description: Cantaloupe server
Parameters:
  StackName:
    Type: String
    Description: Name of the ElasticBeanstalk environment
  ResourceName:
    Type: String
    Description: Name of the resource (for tagging)
    Default: cantaloupe
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the ECS instances
  PublicSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of an existing subnet IDs to use for the load balancer
  PrivateSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of an existing subnet IDs to use for the auto scaling group
  S3Bucket:
    Type: String
    Description: S3 bucket with the cantaloupe war
  S3Key:
    Type: String
    Description: S3 key to the cantaloupe war
  MinSize:
    Type: Number
    Description: Minimum number of instances
  MaxSize:
    Type: Number
    Description: Maximum number of instances
  SecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: A list of security groups, such as sg-a123fd85.
  InstanceType:
    Type: String
    Description: The EC2 instance type
  TiffBucket:
    Type: String
    Description: S3 Bucket where pyramid TIFFs will be stored
Resources:
  TiffBucketUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
      - PolicyDocument:
          Statement:
          - Effect: Allow
            Action: s3:ListAllMyBuckets
            Resource: arn:aws:s3:::*
          - Effect: Allow
            Action:
            - s3:ListBucket
            - s3:GetBucketLocation
            Resource: !Sub arn:aws:s3:::${TiffBucket}
          - Effect: Allow
            Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
            Resource: !Sub arn:aws:s3:::${TiffBucket}/*
        PolicyName: !Sub '${AWS::StackName}-FcrepoS3Access'
  TiffBucketAccess:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref TiffBucketUser
  CantaloupeApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Sub '${StackName}-${ResourceName}'
      Description: Cantaloupe service
  CantaloupeApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref 'CantaloupeApplication'
      Description: Cantaloupe service version
      SourceBundle:
        S3Bucket: !Ref 'S3Bucket'
        S3Key: !Ref 'S3Key'
  CantaloupeConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !Ref 'CantaloupeApplication'
      Description: Cantaloupe configuration template
      OptionSettings:
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: InstanceType
        Value: !Ref 'InstanceType'
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: EC2KeyName
        Value: !Ref 'KeyName'
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: SSHSourceRestriction
        Value: tcp, 22, 22, 10.0.0.0/16
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: SecurityGroups
        Value: !Join [ ',', !Ref 'SecurityGroups' ]
      - Namespace: aws:elb:loadbalancer
        OptionName: CrossZone
        Value: 'true'
      - Namespace: aws:elb:policies
        OptionName: ConnectionDrainingEnabled
        Value: 'true'
      - Namespace: aws:ec2:vpc
        OptionName: Subnets
        Value: !Join [ ',', !Ref 'PrivateSubnets' ]
      - Namespace: aws:ec2:vpc
        OptionName: ELBSubnets
        Value: !Join [ ',', !Ref 'PublicSubnets' ]
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value: !Ref 'EC2InstanceProfile'
      - Namespace: aws:autoscaling:asg
        OptionName: MinSize
        Value: !Ref 'MinSize'
      - Namespace: aws:autoscaling:asg
        OptionName: MaxSize
        Value: !Ref 'MaxSize'
      - Namespace: aws:autoscaling:trigger
        OptionName: LowerBreachScaleIncrement
        Value: '0'
      - Namespace: aws:autoscaling:trigger
        OptionName: UpperBreachScaleIncrement
        Value: '0'
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced
      - Namespace: aws:elasticbeanstalk:application
        OptionName: Application Healthcheck URL
        Value: HTTP:8182/iiif/2
      - Namespace: aws:elb:listener:80
        OptionName: ListenerProtocol
        Value: HTTP
      - Namespace: aws:elb:listener:80
        OptionName: InstancePort
        Value: '8182'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: TIFF_BUCKET
        Value: !Ref 'TiffBucket'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: AWS_ACCESS_KEY_ID
        Value: !Ref 'TiffBucketAccess'
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: AWS_SECRET_KEY
        Value: !Sub '${TiffBucketAccess.SecretAccessKey}'
      SolutionStackName: 64bit Amazon Linux 2017.03 v2.7.1 running Multi-container Docker 17.03.1-ce (Generic)
  CantaloupeEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref 'CantaloupeApplication'
      Description: Cantaloupe Environment
      EnvironmentName: !Sub '${StackName}-${ResourceName}'
      TemplateName: !Ref 'CantaloupeConfigurationTemplate'
      VersionLabel: !Ref 'CantaloupeApplicationVersion'
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
      - arn:aws:iam::aws:policy/AWSElasticBeanstalkMulticontainerDocker
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
      - !Ref 'EC2Role'
Outputs:
  Endpoint:
    Description: IIIF Endpoint
    Value: !Sub "http://${CantaloupeEnvironment.EndpointURL}/iiif/2/"
    Export:
      Name: !Sub '${StackName}-${ResourceName}-Endpoint'
